"""Render tb/perf measurement records (JSON) as Markdown (issue #54).

  python tb/perf/report.py RESULTS.json                     # baseline document
  python tb/perf/report.py RESULTS.json --before BASE.json  # before/after table
"""

import argparse
import json


def pct(x):
    return f"{100 * x:.1f}%"


def render_table(records):
    lines = [
        "| Region | K | N | Tiles | Cycles | MAC util (mesh) | MAC util (tiles used) "
        "| Busiest link | Host inject occupancy | Host inject stall |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in records:
        m = r["metrics"]
        lines.append(
            f"| {r['name']} | {r['K']} | {r['N']} | {r['tiles']} | {r['cycles']} "
            f"| {pct(m['util_mesh'])} | {pct(m['util_used'])} | {pct(m['max_link_occupancy'])} "
            f"| {pct(m['host_in_occupancy'])} | {pct(m['host_in_stall'])} |"
        )
    return "\n".join(lines) + "\n"


def render_links(records):
    out = []
    for r in records:
        if r["workload"] != "mnist":
            continue
        m = r["metrics"]
        out += [f"### {r['name']} links", "", "| Link | Occupancy | Stall |", "|---|---:|---:|"]
        out += [f"| {k} | {pct(v)} | {pct(m['link_stall'][k])} |" for k, v in sorted(m["link_occupancy"].items())]
        out.append("")
    return "\n".join(out)


def render_document(records):
    return "\n".join([
        "# Performance baseline",
        "",
        "Generated by the tb/perf measurement harness (issue #54).",
        "Regenerate with `cd tb/perf && make baseline`; compare a change against it with `cd tb/perf && make compare`.",
        "Every region is checked bit-exact against NumPy before it is recorded.",
        "MAC utilization is fed MACs over 64 MACs per cycle per tile, against all 4 mesh tiles and against the tiles the region used.",
        "Link occupancy is flits moved per cycle on one directed link; the host inject port is node (0,0)'s LOCAL router input, which the host and tile (0,0)'s result stream share.",
        "",
        "## Regions",
        "",
        render_table(records),
        "## MNIST link detail",
        "",
        render_links(records),
    ])


def render_compare(before, after):
    base = {r["name"]: r for r in before}
    lines = [
        "| Region | Cycles before | Cycles after | Speedup | MAC util (mesh) before | MAC util (mesh) after |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for r in after:
        b = base.get(r["name"])
        util_after = pct(r["metrics"]["util_mesh"])
        if b is None:
            lines.append(f"| {r['name']} | - | {r['cycles']} | new | - | {util_after} |")
        else:
            lines.append(
                f"| {r['name']} | {b['cycles']} | {r['cycles']} | {b['cycles'] / r['cycles']:.2f}x "
                f"| {pct(b['metrics']['util_mesh'])} | {util_after} |"
            )
    after_names = {r["name"] for r in after}
    lines += [f"| {n} | {base[n]['cycles']} | - | dropped | - | - |" for n in base if n not in after_names]
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("results")
    ap.add_argument("--before")
    args = ap.parse_args(argv)
    with open(args.results) as f:
        after = json.load(f)
    if args.before:
        with open(args.before) as f:
            print(render_compare(json.load(f), after), end="")
    else:
        print(render_document(after), end="")


if __name__ == "__main__":
    main()
