"""Render tb/accel's CIFAR-10 record (test_accel.py, CIFAR_RESULTS) as the
Markdown in docs/perf/cifar.md.

    python cifar_report.py docs/perf/cifar.json > docs/perf/cifar.md"""

import json
import sys


# rtl/cmd_perf.v's partition of the run cycles, every category measured at
# node (0,0)'s injection port: report label -> counter.
SPLIT = {"OPERAND flits": "slot_cyc", "GO flits": "go_cyc", "Injection stall": "inj_stall_cyc",
         "WAIT/END stall": "wait_cyc", "Credit stall": "credit_cyc", "Other": "other_cyc"}


def check_split(c, where="counters"):
    """The categories must sum to exactly run_cyc: each run cycle is in one."""
    total = sum(c[k] for k in SPLIT.values())
    if total != c["run_cyc"]:
        raise ValueError(f"{where}: the cycle categories sum to {total}, not run_cyc {c['run_cyc']}")


def pct(x):
    return f"{100 * x:.2f}%"


def render(r):
    if r["reference_agreement"] != 1.0:
        raise ValueError("RTL predictions differ from the NumPy reference; not a bit-exact run")
    c = r["counters"]
    check_split(c)
    lines = [
        "# CIFAR-10 on the chip",
        "",
        "Generated by `make cifar` in `tb/accel/` (`tb/accel/cifar_report.py`); do not edit by hand.",
        "",
        f"The frozen CIFAR-10 network ran on `rtl/accel.v` ({r['mesh']} mesh) over {r['images']} test images from one `start` pulse.",
        "The final activation memory is bit-exact against `compiler/golden.py`, and every image's logits and the last image's activations at every layer are bit-exact against `model/cifar_reference.py`.",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Images | {r['images']} |",
        f"| int8 accuracy (RTL logits vs labels) | {pct(r['int8_accuracy'])} |",
        f"| Float model accuracy (same images) | {pct(r['float_accuracy'])} |",
        f"| RTL agrees with the float model | {pct(r['float_agreement'])} |",
        f"| Cycles | {r['cycles']:,} |",
        f"| Cycles per image | {r['cycles_per_image']:,.0f} |",
        f"| OPERAND slot utilization | {100 * r['slot_utilization']:.1f}% |",
        "",
        "Command processor counters (`rtl/cmd_perf.v`).",
        "`" + "`, `".join(SPLIT.values()) + "` partition `run_cyc`, all measured at node (0,0)'s injection port.",
        "",
        "| Counter | Value |",
        "|---|---:|",
    ]
    lines += [f"| {k} | {v:,} |" for k, v in c.items()]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    with open(sys.argv[1]) as f:
        sys.stdout.write(render(json.load(f)))
