"""The mesh scaling study (issue #73): tb/accel's CIFAR-10 records
(test_accel.py, CIFAR_RESULTS), one per mesh shape, combined into
docs/perf/scaling.json and rendered as docs/perf/scaling.md.

    python scaling_report.py combine docs/perf/scaling.json 1x1.json 2x2.json ...
    python scaling_report.py render docs/perf/scaling.json > docs/perf/scaling.md"""

import json
import sys

# The saturation point: the smallest mesh within this fraction of the
# fastest mesh measured.
SATURATION_TOLERANCE = 0.05


def tiles(r):
    return len(r["mesh_perf"]["feed_cyc"])


def combine(records):
    """One record per mesh, fewest tiles first; all bit-exact, same images."""
    records = sorted(records, key=lambda r: (tiles(r), r["mesh"]))
    if len({r["mesh"] for r in records}) != len(records):
        raise ValueError("two records for the same mesh")
    if len({r["images"] for r in records}) != 1:
        raise ValueError("records ran different numbers of images")
    for r in records:
        if r["reference_agreement"] != 1.0:
            raise ValueError(f"{r['mesh']}: RTL predictions differ from the NumPy reference")
        if sum(r["mesh_perf"]["feed_cyc"]) != r["counters"]["slot_cyc"]:
            raise ValueError(f"{r['mesh']}: tiles fed a different number of slots than the DMA sent")
    return records


def derive(r):
    """Per-mesh figures, all per image or as a fraction of run cycles."""
    c, corner, n = r["counters"], r["mesh_perf"]["corner"], r["images"]
    run = c["run_cyc"]
    feed = sum(r["mesh_perf"]["feed_cyc"])
    other = run - c["slot_cyc"] - c["blocks"] - c["inj_stall_cyc"] - c["wait_cyc"] - c["credit_cyc"]
    return {
        "mesh": r["mesh"], "tiles": tiles(r), "cpi": run / n,
        # Every OPERAND and GO flit enters through node (0,0)'s injection
        # port at one flit per cycle: no mesh runs faster than this.
        "floor": (c["slot_cyc"] + c["blocks"]) / n,
        "throughput": feed / run,               # tile-equivalents of 64-MAC feeds per cycle
        "mac_util": feed / (tiles(r) * run),    # per tile
        "inj_busy": corner["lcl_in_xfer"] / run,
        "inj_stall": corner["lcl_in_stall"] / run,
        "link_e": corner["out_xfer_e"] / run, "link_n": corner["out_xfer_n"] / run,
        "local_out": corner["out_xfer_l"] / run,
        "split": {"OPERAND slots": c["slot_cyc"], "GO beats": c["blocks"], "Injection stall": c["inj_stall_cyc"],
                  "WAIT/END stall": c["wait_cyc"], "Credit stall": c["credit_cyc"], "Other": other},
        "run": run, "other_per_block": other / c["blocks"], "blocks_per_image": c["blocks"] / n,
        "slots_per_block": c["slot_cyc"] / c["blocks"],
    }


def pct(x):
    return f"{100 * x:.1f}%"


def mermaid_bar_line(title, xs, y_label, bars, line, y_max):
    return ["```mermaid", "xychart-beta", f'    title "{title}"',
            "    x-axis [" + ", ".join(f'"{x}"' for x in xs) + "]",
            f'    y-axis "{y_label}" 0 --> {y_max}',
            "    bar [" + ", ".join(f"{b:.4g}" if b < 100 else f"{b:.0f}" for b in bars) + "]",
            "    line [" + ", ".join(f"{v:.4g}" if v < 100 else f"{v:.0f}" for v in line) + "]",
            "```"]


def render(records):
    d = [derive(r) for r in combine(records)]
    base, best = d[0], min(d, key=lambda x: x["cpi"])
    sat = next(x for x in d if x["cpi"] <= best["cpi"] * (1 + SATURATION_TOLERANCE))
    after = [x for x in d if x["tiles"] > sat["tiles"]]
    two = next((x for x in d if x["tiles"] == 2), None)
    shapes = [x["mesh"] for x in d]
    r0 = records[0]
    y_max = int(-(-max(x["cpi"] for x in d) * 1.1 // 50_000) * 50_000)

    lines = [
        "# Mesh scaling study",
        "",
        "Generated by `make scaling` in `tb/accel/` (`tb/accel/scaling_report.py`); do not edit by hand.",
        "",
        f"The frozen CIFAR-10 program, recompiled for each mesh, ran on `rtl/accel.v` over {r0['images']} test images per mesh from one `start` pulse.",
        "Every run's final activation memory is bit-exact against `compiler/golden.py`, and its logits and last-image activations are bit-exact against `model/cifar_reference.py`.",
        f"int8 accuracy is {pct(r0['int8_accuracy'])} on every mesh: the mesh changes the schedule, never the result.",
        "",
        "## Results",
        "",
        "| Mesh | Tiles | Cycles per image | Speedup vs " + base["mesh"] + " | Mesh throughput (tiles busy) | MAC utilization per tile | Corner injection busy | Corner injection stalled |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    lines += [f"| {x['mesh']} | {x['tiles']} | {x['cpi']:,.0f} | {base['cpi'] / x['cpi']:.2f}x | {x['throughput']:.2f} | "
              f"{pct(x['mac_util'])} | {pct(x['inj_busy'])} | {pct(x['inj_stall'])} |" for x in d]
    lines += [
        "",
        "- *Mesh throughput* is 64-MAC operand slots fed into all arrays per cycle: 1.00 would be one tile computing every cycle.",
        "- *Corner injection* is node (0,0)'s router LOCAL input, where every OPERAND and GO flit enters the mesh and tile (0,0)'s RESULT flits leave it (`rtl/node_perf.v` `lcl_in_xfer`/`lcl_in_stall` over run cycles).",
        "",
        f"Measured cycles per image (bars) against the injection-port floor of {best['floor']:,.0f} cycles per image (line):",
        "",
    ]
    lines += mermaid_bar_line("Cycles per CIFAR-10 image", shapes, "Cycles per image",
                              [x["cpi"] for x in d], [x["floor"] for x in d], y_max)
    lines += ["", f"Measured speedup over {base['mesh']} (bars) against linear scaling in the tile count (line):", ""]
    lines += mermaid_bar_line(f"Speedup over {base['mesh']}", shapes, "Speedup",
                              [base["cpi"] / x["cpi"] for x in d], [x["tiles"] / base["tiles"] for x in d],
                              d[-1]["tiles"] // base["tiles"])
    lines += [
        "",
        "## Where the command processor's cycles go",
        "",
        "Run cycles by what the command processor did (`rtl/cmd_perf.v`); *Other* is the remainder.",
        "",
        "| Mesh | " + " | ".join(d[0]["split"]) + " |",
        "|---|" + "---:|" * len(d[0]["split"]),
    ]
    lines += [f"| {x['mesh']} | " + " | ".join(pct(v / x["run"]) for v in x["split"].values()) + " |" for x in d]
    lines += [
        "",
        "Node (0,0)'s outgoing ports, busy cycles over run cycles:",
        "",
        "| Mesh | East link | North link | LOCAL out (tile (0,0)'s operands, all RESULTs) |",
        "|---|---:|---:|---:|",
    ]
    lines += [f"| {x['mesh']} | {pct(x['link_e'])} | {pct(x['link_n'])} | {pct(x['local_out'])} |" for x in d]

    gain = (f"no larger mesh measured is more than {pct(sat['cpi'] / min(x['cpi'] for x in after) - 1)} faster"
            if after else "no larger mesh was measured")
    lines += [
        "",
        "## Where the corner saturates and why",
        "",
        f"The corner saturates at **{sat['mesh']}**: it runs within {pct(sat['cpi'] / best['cpi'] - 1)} of the fastest mesh measured ({best['mesh']}), and {gain}, "
        f"while the tile count grows {d[-1]['tiles'] // sat['tiles']}x.",
        "",
        "**The corner's injection port is the bottleneck, and its capacity is exactly one tile.**",
        "Every OPERAND and GO flit enters the mesh through node (0,0)'s single router LOCAL input, one flit per cycle.",
        "One OPERAND flit is one slot, an 8-byte A column and an 8-byte B row, which is 64 MACs of work for the tile it reaches: one tile's peak rate.",
        "So no mesh can do more MACs per cycle than one fully busy tile.",
        f"Each image needs {best['floor']:,.0f} injected flits ({best['blocks_per_image']:,.0f} BLOCKs of {best['slots_per_block']:.1f} slots on average, plus one GO each), which is a floor under every mesh; "
        f"{best['mesh']} runs at {pct(best['floor'] / best['cpi'])} of the floor's speed, with the corner's injection port busy {pct(best['inj_busy'])} of cycles.",
        f"Mesh throughput tops out at {max(x['throughput'] for x in d):.2f} tiles busy, and MAC utilization per tile falls from {pct(d[0]['mac_util'])} to {pct(d[-1]['mac_util'])} as tiles are added.",
        "",
        "**Below saturation, a single tile cannot overlap loading and computing.**",
        f"A tile backpressures OPERAND and GO flits while it computes and streams results (issue #44, one operand buffer), so on {base['mesh']} loading and computing take turns: "
        f"the corner's injection port is stalled {pct(base['inj_stall'])} of cycles and the mesh runs at {pct(base['floor'] / base['cpi'])} of the floor's speed.",
    ]
    if two:
        lines.append(f"A second tile loads while the first computes: {two['mesh']} is {base['cpi'] / two['cpi']:.2f}x faster than {base['mesh']}, "
                     f"and the larger meshes hide the stalls that remain (the injection stall falls to {pct(best['inj_stall'])} on {best['mesh']}).")
    lines += [
        "",
        f"**The rest is a fixed cost per BLOCK.** Past the slots, the GO beats, and the stalls, the command processor spends {best['other_per_block']:.2f} cycles per BLOCK on {best['mesh']} "
        f"({', '.join(f"{x['other_per_block']:.2f}" for x in d)} across the meshes), independent of the mesh.",
        "That matches `rtl/dma_gather.v`'s three-stage pipeline (S0, S1, S2) refilling between BLOCKs: `done` pulses when the GO beat is accepted, and `rtl/cmd_seq.v` starts the next BLOCK only then, so each BLOCK's first slot waits for the pipeline to fill again.",
        "",
        "What this decides for the next phase is recorded in `docs/decisions.md` (2026-09-28, mesh scaling study).",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    if sys.argv[1] == "combine":
        recs = []
        for p in sys.argv[3:]:
            with open(p) as f:
                recs.append(json.load(f))
        with open(sys.argv[2], "w") as f:
            json.dump(combine(recs), f, indent=2)
    elif sys.argv[1] == "render":
        with open(sys.argv[2]) as f:
            sys.stdout.write(render(json.load(f)))
    else:
        sys.exit(__doc__)
